import type {
  Category,
  HistoricalEvent,
  Media,
  Period,
  Profile,
  PostgrestCategory,
  PostgrestHistoricalEvent,
  PostgrestMedia,
  PostgrestPeriod,
  PostgrestProfile,
  PostgrestStory,
  PostgrestTimeline,
  Story,
  Timeline,
} from '../models';

export const mapApiStoryToModel = ({
  user_id: userId,
  slug,
  title,
  sub_title: subTitle,
  summary,
  detail,
  periods,
}: PostgrestStory): Story => ({
  userId,
  slug,
  title,
  subTitle: subTitle ?? null,
  summary: summary ?? null,
  detail: detail ?? null,
  periods: periods?.map((p) => mapApiPeriodToModel(p)) ?? [],
});

export const mapApiPeriodToModel = ({
  user_id: userId,
  slug,
  title,
  summary,
  begin_date: beginDate,
  end_date: endDate,
  timelines,
}: PostgrestPeriod): Period => ({
  userId,
  slug,
  title,
  summary: summary ?? null,
  beginDate,
  endDate,
  timelines: timelines?.map((t) => mapApiTimelineToModel(t)) ?? [],
});

export const mapApiTimelineToModel = ({
  user_id: userId,
  slug,
  title,
  summary,
  scale,
  begin_date: beginDate,
  end_date: endDate,
  historical_events: events,
  periods,
}: PostgrestTimeline): Timeline => ({
  userId,
  slug,
  title,
  summary: summary ?? null,
  scale: scale ?? null,
  beginDate,
  endDate,
  events: events?.map((e) => mapApiEventToModel(e)) ?? [],
  periods: periods?.map((p) => mapApiPeriodToModel(p)) ?? [],
});

export const mapApiEventToModel = ({
  user_id: userId,
  slug,
  title,
  summary,
  detail,
  categories,
  importance,
  location,
  begin_date: beginDate,
  end_date: endDate,
  media,
  timelines,
}: PostgrestHistoricalEvent): HistoricalEvent => ({
  userId,
  slug,
  title,
  summary,
  detail,
  categories: categories?.map((c) => mapApiCategoryToModel(c)) ?? [],
  importance,
  location,
  beginDate,
  endDate,
  media: media?.map((m) => mapApiMediaToModel(m)) ?? [],
  timelines: timelines?.map((t) => mapApiTimelineToModel(t)) ?? [],
});

export const mapApiCategoryToModel = ({
  user_id: userId,
  slug,
  title,
  events,
}: PostgrestCategory): Category => ({
  userId,
  slug,
  title,
  events: events?.map((e) => mapApiEventToModel(e)) ?? [],
});

export const mapApiMediaToModel = ({
  user_id: userId,
  slug,
  alternativetext: alternativeText,
  caption,
  url,
  width,
  height,
  formats,
}: PostgrestMedia): Media => ({
  userId,
  slug,
  alternativeText,
  caption,
  url,
  width,
  height,
  formats,
});

export const mapApiProfileToModel = ({
  id,
  first_name: firstName,
  last_name: lastName,
  username: userName,
  bio,
  avatar_url: avatarUrl,
  website,
  social_x: socialX,
  social_facebook: socialFacebook,
  social_instagram: socialInstagram,
  social_pinterest: socialPinterest,
  social_youtube: socialYouTube,
}: PostgrestProfile): Profile => ({
  id,
  firstName,
  lastName,
  userName,
  bio,
  avatarUrl,
  website,
  socialX,
  socialFacebook,
  socialInstagram,
  socialPinterest,
  socialYouTube,
});
