import {Period} from 'service'

export const periods: Period[] = [{
  title: 'Period One',
  slug: 'period-one',
  summary: 'The first period in the series.',
  beginDate: '1',
  endDate: '2',
  timelines: [{
    slug: 'first-period-one-timeline',
    title: 'The First Period One Timeline',
    summary: 'The first timeline of the first period. Est culpa qui qui tempore ex qui quis. Consequatur et laborum quia. Magnam voluptas delectus laudantium molestiae. Assumenda dolorem aliquid et possimus atque repellat illo. Molestiae repellat delectus consequatur numquam ipsa nisi. Excepturi doloribus laudantium laboriosam et consequatur aperiam doloremque.',
    scale: 'The timeline scale (1:1,000,000)',
    beginDate: '1',
    endDate: '1',
    events: [],
    periods: [],
  },{
    slug: 'second-period-one-timeline',
    title: 'The Second Period One Timeline',
    summary: 'The second timeline of the first period. Est culpa qui qui tempore ex qui quis. Consequatur et laborum quia. Magnam voluptas delectus laudantium molestiae. Assumenda dolorem aliquid et possimus atque repellat illo. Molestiae repellat delectus consequatur numquam ipsa nisi. Excepturi doloribus laudantium laboriosam et consequatur aperiam doloremque.',
    scale: 'The timeline scale (1:1,000,000)',
    beginDate: '2',
    endDate: '2',
    events: [],
    periods: [],
  }],
},{
  title: 'Period Two',
  slug: 'period-two',
  summary: 'The second period in the series.',
  beginDate: '2',
  endDate: '3',
  timelines: [{
    slug: 'first-period-two-timeline',
    title: 'The First Period Two Timeline',
    summary: 'The first timeline of the second period. Est culpa qui qui tempore ex qui quis. Consequatur et laborum quia. Magnam voluptas delectus laudantium molestiae. Assumenda dolorem aliquid et possimus atque repellat illo. Molestiae repellat delectus consequatur numquam ipsa nisi. Excepturi doloribus laudantium laboriosam et consequatur aperiam doloremque.',
    scale: 'The timeline scale (1:1,000,000)',
    beginDate: '2',
    endDate: '2',
    events: [],
    periods: [],
  },{
    slug: 'second-period-two-timeline',
    title: 'The Second Period Two Timeline',
    summary: 'The second timeline of the second period. Est culpa qui qui tempore ex qui quis. Consequatur et laborum quia. Magnam voluptas delectus laudantium molestiae. Assumenda dolorem aliquid et possimus atque repellat illo. Molestiae repellat delectus consequatur numquam ipsa nisi. Excepturi doloribus laudantium laboriosam et consequatur aperiam doloremque.',
    scale: 'The timeline scale (1:1,000,000)',
    beginDate: '3',
    endDate: '3',
    events: [],
    periods: [],
  }],

},{
  title: 'Period Three',
  slug: 'period-three',
  summary: 'The third period in the series.',
  beginDate: '3',
  endDate: '4',
  timelines: [{
    slug: 'first-period-three-timeline',
    title: 'The First Period Three Timeline',
    summary: 'The first timeline of the third period. Est culpa qui qui tempore ex qui quis. Consequatur et laborum quia. Magnam voluptas delectus laudantium molestiae. Assumenda dolorem aliquid et possimus atque repellat illo. Molestiae repellat delectus consequatur numquam ipsa nisi. Excepturi doloribus laudantium laboriosam et consequatur aperiam doloremque.',
    scale: 'The timeline scale (1:1,000,000)',
    beginDate: '3',
    endDate: '3',
    events: [],
    periods: [],
  },{
    slug: 'second-period-three-timeline',
    title: 'The Second Period Three Timeline',
    summary: 'The second timeline of the third period. Est culpa qui qui tempore ex qui quis. Consequatur et laborum quia. Magnam voluptas delectus laudantium molestiae. Assumenda dolorem aliquid et possimus atque repellat illo. Molestiae repellat delectus consequatur numquam ipsa nisi. Excepturi doloribus laudantium laboriosam et consequatur aperiam doloremque.',
    scale: 'The timeline scale (1:1,000,000)',
    beginDate: '4',
    endDate: '4',
    events: [],
    periods: [],
  }],

},{
  title: 'Period Four',
  slug: 'period-four',
  summary: 'The fourth period in the series.',
  beginDate: '4',
  endDate: '5',
  timelines: [{
    slug: 'first-period-four-timeline',
    title: 'The First Period Four Timeline',
    summary: 'The first timeline of the fourth period. Est culpa qui qui tempore ex qui quis. Consequatur et laborum quia. Magnam voluptas delectus laudantium molestiae. Assumenda dolorem aliquid et possimus atque repellat illo. Molestiae repellat delectus consequatur numquam ipsa nisi. Excepturi doloribus laudantium laboriosam et consequatur aperiam doloremque.',
    scale: 'The timeline scale (1:1,000,000)',
    beginDate: '4',
    endDate: '4',
    events: [],
    periods: [],
  },{
    slug: 'second-period-four-timeline',
    title: 'The Second Period Four Timeline',
    summary: 'The second timeline of the fourth period. Est culpa qui qui tempore ex qui quis. Consequatur et laborum quia. Magnam voluptas delectus laudantium molestiae. Assumenda dolorem aliquid et possimus atque repellat illo. Molestiae repellat delectus consequatur numquam ipsa nisi. Excepturi doloribus laudantium laboriosam et consequatur aperiam doloremque.',
    scale: 'The timeline scale (1:1,000,000)',
    beginDate: '5',
    endDate: '5',
    events: [],
    periods: [],
  }],

},{
  title: 'Period Five',
  slug: 'period-five',
  summary: 'The fifth period in the series.',
  beginDate: '5',
  endDate: '6',
  timelines: [{
    slug: 'first-period-five-timeline',
    title: 'The First Period Five Timeline',
    summary: 'The first timeline of the fifth period. Est culpa qui qui tempore ex qui quis. Consequatur et laborum quia. Magnam voluptas delectus laudantium molestiae. Assumenda dolorem aliquid et possimus atque repellat illo. Molestiae repellat delectus consequatur numquam ipsa nisi. Excepturi doloribus laudantium laboriosam et consequatur aperiam doloremque.',
    scale: 'The timeline scale (1:1,000,000)',
    beginDate: '5',
    endDate: '5',
    events: [],
    periods: [],
  },{
    slug: 'second-period-five-timeline',
    title: 'The Second Period Five Timeline',
    summary: 'The second timeline of the fifth period. Est culpa qui qui tempore ex qui quis. Consequatur et laborum quia. Magnam voluptas delectus laudantium molestiae. Assumenda dolorem aliquid et possimus atque repellat illo. Molestiae repellat delectus consequatur numquam ipsa nisi. Excepturi doloribus laudantium laboriosam et consequatur aperiam doloremque.',
    scale: 'The timeline scale (1:1,000,000)',
    beginDate: '6',
    endDate: '6',
    events: [],
    periods: [],
  }],

},{
  title: 'Period Six',
  slug: 'period-six',
  summary: 'The sixth period in the series.',
  beginDate: '6',
  endDate: '7',
  timelines: [{
    slug: 'first-period-six-timeline',
    title: 'The First Period Six Timeline',
    summary: 'The first timeline of the sixth period. Est culpa qui qui tempore ex qui quis. Consequatur et laborum quia. Magnam voluptas delectus laudantium molestiae. Assumenda dolorem aliquid et possimus atque repellat illo. Molestiae repellat delectus consequatur numquam ipsa nisi. Excepturi doloribus laudantium laboriosam et consequatur aperiam doloremque.',
    scale: 'The timeline scale (1:1,000,000)',
    beginDate: '6',
    endDate: '6',
    events: [],
    periods: [],
  },{
    slug: 'second-period-six-timeline',
    title: 'The Second Period Six Timeline',
    summary: 'The second timeline of the sixth period. Est culpa qui qui tempore ex qui quis. Consequatur et laborum quia. Magnam voluptas delectus laudantium molestiae. Assumenda dolorem aliquid et possimus atque repellat illo. Molestiae repellat delectus consequatur numquam ipsa nisi. Excepturi doloribus laudantium laboriosam et consequatur aperiam doloremque.',
    scale: 'The timeline scale (1:1,000,000)',
    beginDate: '7',
    endDate: '7',
    events: [],
    periods: [],
  }],

}];
